### ISSUE TITLE
Deploy on Netlify

### ISSUE THREAD

**Issue by gmacario** [gmacario/gmacario.github.io#180]
See PoC at https://blog.gmacario.it/

Project: https://app.netlify.com/sites/stoic-newton-ff8d72/settings/deploys

**Comment by gmacario** [comment]
Here is a comparison between Netlify, Vercel and GitHub Pages: https://www.jondjones.com/frontend/jamstack/best-nextjs-hosting-provider-netlify-vs-vercel-vs-github-pages

**Comment by gmacario** [comment]
# Implementation plan: Netlify as staging/preview environment (2026-07-20)

Plan produced after a stress-testing session on 2026-07-20. The 2023 PoC
(<https://blog.gmacario.it/>, Netlify site `stoic-newton-ff8d72`) is still live but serving a
stale snapshot, configured only in the Netlify UI (no `netlify.toml` in the repo).

## Decisions taken

| Decision | Choice |
| --- | --- |
| Role of Netlify | **Staging + PR deploy previews.** <https://gmacario.github.io/> stays the canonical production site on GitHub Pages. Netlify replaces the dead Heroku `stage` job in `build-and-deploy.yml` (its `git push heroku` has been commented out since forever). |
| Build driver | **Netlify GitHub integration** with a committed `netlify.toml` (config as code). No Netlify tokens/secrets in GitHub Actions. |
| Netlify site | **Reuse `stoic-newton-ff8d72`** — keeps the `blog.gmacario.it` custom domain, DNS and TLS cert. First successful deploy replaces the stale snapshot. Optionally rename the site to something meaningful (e.g. `gmacario-blog`). |
| Stack | **Pin Node 14** to match the current GitHub Actions build; the Next.js 10 → current / Node upgrade is explicitly out of scope (separate issue). |
| SEO / indexing | `blog.gmacario.it` **stays indexable** (keeps the door open to promoting it to primary later). **No** `rel=canonical` tag for now — accept the duplicate-content ambiguity; revisit if/when the primary domain changes. |
| Heroku leftovers | **Removed in this issue** once Netlify previews are proven working. |

## Phase 1 — Config as code

- [ ] Add `netlify.toml` to the repo root:

  ```toml
  [build]
    command = "npm run export"   # = next build && next export -o _static
    publish = "_static"

  [build.environment]
    NODE_VERSION = "14"
  ```

- [ ] Verify the build reproduces locally with Node 14: `npm ci && npm run export`, then spot-check `_static/` (index, a couple of posts, assets under `/public`). Note: `touch _static/.nojekyll` is a GitHub Pages requirement only; Netlify doesn't need it.

## Phase 2 — Re-link the Netlify site

- [ ] In the Netlify UI, open site `stoic-newton-ff8d72` and link it to `gmacario/gmacario.github.io`, production branch `main`. Confirm the build settings are read from `netlify.toml` (clear any conflicting UI-configured build command from the 2023 PoC).
- [ ] Enable deploy previews for pull requests, with the Netlify GitHub app posting preview links as PR comments.
- [ ] Trigger a production deploy of `main` and verify <https://blog.gmacario.it/> now serves the same content as <https://gmacario.github.io/> (compare latest posts, styling, assets).

## Phase 3 — Validation

- [ ] Open the `netlify.toml` change as a PR — it doubles as the deploy-preview test. Confirm the preview URL is posted on the PR and the preview site works (internal links, images under `/public`, any feeds).
- [ ] Check Netlify build-minutes consumption fits comfortably in the free tier given typical push frequency.

## Phase 4 — Cleanup and documentation

- [ ] Remove the Heroku `stage` job from `.github/workflows/build-and-deploy.yml`; make `deploy` depend directly on `build`; drop the `HEROKU_*` secret checks and the `staging_environment` reference.
- [ ] Delete the now-unused `HEROKU_API_KEY` / `HEROKU_EMAIL` / `HEROKU_STAGING_APP` repository secrets.
- [ ] Update `README.md`: document the dual setup (production = GitHub Pages, staging/previews = Netlify at `blog.gmacario.it`) and add the Netlify deploy-status badge next to the existing workflow badges.
- [ ] File follow-up issues: (a) Next.js 10 / Node 14 stack upgrade; (b) optional future promotion of `blog.gmacario.it` to primary domain (canonical/redirect strategy deferred until then).

## Risks / notes

- **Node 14 on Netlify's current build image**: must be pinned via `NODE_VERSION` (or `.nvmrc`); if Netlify's image can no longer install Node 14, the stack-upgrade issue becomes a prerequisite rather than a follow-up.
- The stale snapshot on `stoic-newton-ff8d72` is simply overwritten by the first deploy; Netlify keeps deploy history, so rollback is one click.
- Both hosts stay indexable with identical content — accepted consciously; search engines will pick a winner until a canonical decision is made in the follow-up.

## Acceptance criteria

1. Every push to `main` deploys the same content to `blog.gmacario.it` (Netlify) that GitHub Pages serves at `gmacario.github.io`.
2. Every PR gets a working Netlify deploy-preview link as a comment.
3. `netlify.toml` in the repo is the single source of truth for the Netlify build.
4. The Heroku `stage` job and its secrets are gone; `build-and-deploy.yml` stays green.
5. README documents the production/staging split.
